// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */

	void CWE476_NULL_Pointer_Dereference__char_01_good();

	void CWE476_NULL_Pointer_Dereference__char_02_good();

	void CWE476_NULL_Pointer_Dereference__char_03_good();

	void CWE476_NULL_Pointer_Dereference__char_04_good();

	void CWE476_NULL_Pointer_Dereference__char_05_good();

	void CWE476_NULL_Pointer_Dereference__char_06_good();

	void CWE476_NULL_Pointer_Dereference__char_07_good();

	void CWE476_NULL_Pointer_Dereference__char_08_good();

	void CWE476_NULL_Pointer_Dereference__char_09_good();

	void CWE476_NULL_Pointer_Dereference__char_10_good();

	void CWE476_NULL_Pointer_Dereference__char_11_good();

	void CWE476_NULL_Pointer_Dereference__char_12_good();

	void CWE476_NULL_Pointer_Dereference__char_13_good();

	void CWE476_NULL_Pointer_Dereference__char_14_good();

	void CWE476_NULL_Pointer_Dereference__char_15_good();

	void CWE476_NULL_Pointer_Dereference__char_16_good();

	void CWE476_NULL_Pointer_Dereference__char_17_good();

	void CWE476_NULL_Pointer_Dereference__char_18_good();

	void CWE476_NULL_Pointer_Dereference__char_21_good();

	void CWE476_NULL_Pointer_Dereference__char_22_good();

	void CWE476_NULL_Pointer_Dereference__char_31_good();

	void CWE476_NULL_Pointer_Dereference__char_32_good();

	void CWE476_NULL_Pointer_Dereference__char_34_good();

	void CWE476_NULL_Pointer_Dereference__char_41_good();

	void CWE476_NULL_Pointer_Dereference__char_44_good();

	void CWE476_NULL_Pointer_Dereference__char_45_good();

	void CWE476_NULL_Pointer_Dereference__char_51_good();

	void CWE476_NULL_Pointer_Dereference__char_52_good();

	void CWE476_NULL_Pointer_Dereference__char_53_good();

	void CWE476_NULL_Pointer_Dereference__char_54_good();

	void CWE476_NULL_Pointer_Dereference__char_63_good();

	void CWE476_NULL_Pointer_Dereference__char_64_good();

	void CWE476_NULL_Pointer_Dereference__char_65_good();

	void CWE476_NULL_Pointer_Dereference__char_66_good();

	void CWE476_NULL_Pointer_Dereference__char_67_good();

	void CWE476_NULL_Pointer_Dereference__char_68_good();
	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE476_NULL_Pointer_Dereference__char_01_bad();

	void CWE476_NULL_Pointer_Dereference__char_02_bad();

	void CWE476_NULL_Pointer_Dereference__char_03_bad();

	void CWE476_NULL_Pointer_Dereference__char_04_bad();

	void CWE476_NULL_Pointer_Dereference__char_05_bad();

	void CWE476_NULL_Pointer_Dereference__char_06_bad();

	void CWE476_NULL_Pointer_Dereference__char_07_bad();

	void CWE476_NULL_Pointer_Dereference__char_08_bad();

	void CWE476_NULL_Pointer_Dereference__char_09_bad();

	void CWE476_NULL_Pointer_Dereference__char_10_bad();

	void CWE476_NULL_Pointer_Dereference__char_11_bad();

	void CWE476_NULL_Pointer_Dereference__char_12_bad();

	void CWE476_NULL_Pointer_Dereference__char_13_bad();

	void CWE476_NULL_Pointer_Dereference__char_14_bad();

	void CWE476_NULL_Pointer_Dereference__char_15_bad();

	void CWE476_NULL_Pointer_Dereference__char_16_bad();

	void CWE476_NULL_Pointer_Dereference__char_17_bad();

	void CWE476_NULL_Pointer_Dereference__char_18_bad();

	void CWE476_NULL_Pointer_Dereference__char_21_bad();

	void CWE476_NULL_Pointer_Dereference__char_22_bad();

	void CWE476_NULL_Pointer_Dereference__char_31_bad();

	void CWE476_NULL_Pointer_Dereference__char_32_bad();

	void CWE476_NULL_Pointer_Dereference__char_34_bad();

	void CWE476_NULL_Pointer_Dereference__char_41_bad();

	void CWE476_NULL_Pointer_Dereference__char_44_bad();

	void CWE476_NULL_Pointer_Dereference__char_45_bad();

	void CWE476_NULL_Pointer_Dereference__char_51_bad();

	void CWE476_NULL_Pointer_Dereference__char_52_bad();

	void CWE476_NULL_Pointer_Dereference__char_53_bad();

	void CWE476_NULL_Pointer_Dereference__char_54_bad();

	void CWE476_NULL_Pointer_Dereference__char_63_bad();

	void CWE476_NULL_Pointer_Dereference__char_64_bad();

	void CWE476_NULL_Pointer_Dereference__char_65_bad();

	void CWE476_NULL_Pointer_Dereference__char_66_bad();

	void CWE476_NULL_Pointer_Dereference__char_67_bad();

	void CWE476_NULL_Pointer_Dereference__char_68_bad();
	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
	namespace CWE476_NULL_Pointer_Dereference__char_33 { void good();}

	namespace CWE476_NULL_Pointer_Dereference__char_72 { void good();}

	namespace CWE476_NULL_Pointer_Dereference__char_73 { void good();}

	namespace CWE476_NULL_Pointer_Dereference__char_74 { void good();}

	namespace CWE476_NULL_Pointer_Dereference__char_81 { void good();}

	namespace CWE476_NULL_Pointer_Dereference__char_82 { void good();}

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
	namespace CWE476_NULL_Pointer_Dereference__char_33 { void bad();}

	namespace CWE476_NULL_Pointer_Dereference__char_72 { void bad();}

	namespace CWE476_NULL_Pointer_Dereference__char_73 { void bad();}

	namespace CWE476_NULL_Pointer_Dereference__char_74 { void bad();}

	namespace CWE476_NULL_Pointer_Dereference__char_81 { void bad();}

	namespace CWE476_NULL_Pointer_Dereference__char_82 { void bad();}
	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
