// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_01_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_02_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_03_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_04_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_05_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_06_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_07_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_08_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_09_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_10_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_11_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_12_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_13_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_14_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_15_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_16_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_17_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_18_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_21_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_22_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_31_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_32_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_34_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_41_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_42_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_44_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_45_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_51_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_52_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_53_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_54_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_61_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_63_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_64_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_65_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_66_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_67_good();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_68_good();
	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_01_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_02_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_03_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_04_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_05_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_06_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_07_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_08_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_09_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_10_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_11_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_12_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_13_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_14_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_15_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_16_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_17_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_18_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_21_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_22_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_31_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_32_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_34_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_41_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_42_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_44_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_45_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_51_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_52_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_53_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_54_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_61_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_63_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_64_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_65_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_66_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_67_bad();

	void CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_68_bad();
	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_33 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_43 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_62 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_72 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_73 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_74 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_81 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_82 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_83 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_83 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_84 { void good();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_84 { void good();}
	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_33 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_43 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_62 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_72 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_73 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_74 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_81 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_82 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_83 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_83 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_84 { void bad();}

	namespace CWE122_Heap_Based_Buffer_Overflow__CWE131_loop_84 { void bad();}
	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
